[project]
name = "ai-tracker-correlator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scipy>=1.17.0",
    "scipy-stubs~=1.17.0",
    "torch>=2.10.0",
    "torch-geometric>=2.7.0",
]
